[tool.ruff]
target-version = "py38"

[tool.ruff.lint]
extend-select = [
  "UP", # see pyupgrade
  "B",  # see flake8-bugbear
  "A", # see flake8-builtins 
  "C4", # see flake8-comprehension 
  "SIM", # see flake8-simplify
  "TCH", # see flake8-type-checking
]
